(()=>{
const ICONS=Array.isArray(window.ICON_DATA)?window.ICON_DATA:[], META=Array.isArray(window.SOURCE_META)?window.SOURCE_META:[];const PAGE=260;let active='all',shown=PAGE,current=null,filtered=[],toastTimer;const $=s=>document.querySelector(s),grid=$('#grid'),search=$('#search'),details=$('#details'),favorites=new Set(JSON.parse(localStorage.getItem('omniIconFavorites')||'[]'));
const metaBy=Object.fromEntries(META.map(x=>[x.source,x]));const labelFor=s=>metaBy[s]?.label||s;
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function norm(s=''){return String(s).toLowerCase().replace(/[-_]+/g,' ')}function key(i){return i.id||`${i.source}:${i.style||''}:${i.name}`}
function buildPacks(){const root=$('#packSources');root.innerHTML=META.map(m=>`<button class="source" data-source="${esc(m.source)}"><span>${esc(m.label)}</span><b>${Number(m.count||0).toLocaleString()}</b></button>`).join('')}
function matchesFilter(i){if(active==='favorites')return favorites.has(key(i));if(active==='kind:brand')return ['brand','favicon'].includes(i.kind);if(active.startsWith('kind:'))return i.kind===active.split(':')[1];if(active!=='all')return i.source===active;return true}
function getFiltered(){const q=norm(search.value.trim()),parts=q.split(/\s+/).filter(Boolean);return ICONS.filter(i=>matchesFilter(i)&&(!q||parts.every(p=>norm([i.name,i.label,i.style,i.source,i.sourceLabel,i.kind,i.url,(i.terms||[]).join(' ')].join(' ')).includes(p))))}
function iconHtml(i,extra=''){if(i.svg)return `<span class="svg-icon render-${esc(i.render||'auto')} ${extra}">${i.svg}</span>`;if(i.raster)return `<img class="raster-icon ${extra}" src="${esc(i.raster)}" alt="">`;if(i.source==='material')return `<span class="material-icon ${extra}">${esc(i.char||'')}</span>`;if(i.source==='nerdfonts')return `<span class="nerd-icon ${extra}">${esc(i.char||'')}</span>`;return `<span class="glyph-icon ${extra}">${esc(i.char||'')}</span>`}
function titleFor(){if(active==='all')return'All icons';if(active==='favorites')return'Favorites';if(active==='kind:ui')return'UI icons';if(active==='kind:brand')return'Brands + Favicons';if(active==='kind:developer')return'Developer icons';return labelFor(active)}
function render(){filtered=getFiltered();const part=filtered.slice(0,shown);grid.innerHTML=part.map((i,n)=>`<article class="icon-card" data-idx="${n}"><span class="kind-pill">${esc(i.kind||'icon')}</span><button class="more" data-detail="${n}">⋯</button><div class="icon">${iconHtml(i)}</div><div class="name">${esc(i.label||i.name)}</div><div class="pack">${esc(labelFor(i.source))}</div></article>`).join('');$('#viewTitle').textContent=titleFor();$('#resultText').textContent=`${filtered.length.toLocaleString()} icons${search.value.trim()?` matching “${search.value.trim()}”`:''}`;$('#empty').classList.toggle('hidden',!!filtered.length);$('#loadMore').classList.toggle('hidden',shown>=filtered.length||!filtered.length)}
async function copy(text,label='Copied'){if(!text){toast('Not available for this icon');return}try{await navigator.clipboard.writeText(text)}catch{const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}toast(label)}function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1300)}
function smart(i){return i.svg?'svg':i.raster?'asset':(i.source==='material'?'html':'glyph')}function val(i,m){if(m==='smart')m=smart(i);if(m==='id')return key(i);if(m==='svg')return i.svg||'';if(m==='glyph')return i.char||'';if(m==='html')return i.html||i.char||'';if(m==='css')return i.css||'';if(m==='asset')return i.raster||'';return''}
grid.addEventListener('click',e=>{const b=e.target.closest('[data-detail]');if(b){e.stopPropagation();open(filtered[+b.dataset.detail]);return}const c=e.target.closest('.icon-card');if(!c)return;const i=filtered[+c.dataset.idx],m=$('#copyMode').value;copy(val(i,m),`Copied ${m==='smart'?smart(i):m}`)});$('#sourceList').addEventListener('click',e=>{const b=e.target.closest('[data-source]');if(!b)return;active=b.dataset.source;shown=PAGE;document.querySelectorAll('.source').forEach(x=>x.classList.toggle('active',x===b));render()});search.addEventListener('input',()=>{shown=PAGE;render()});$('#clearSearch').onclick=()=>{search.value='';shown=PAGE;search.focus();render()};$('#loadMore').onclick=()=>{shown+=PAGE;render()};$('#randomIcon').onclick=()=>filtered.length&&open(filtered[Math.floor(Math.random()*filtered.length)]);
function open(i){current=i;$('#detailPreview').innerHTML=iconHtml(i);$('#detailSource').textContent=`${labelFor(i.source)}${i.style?' · '+i.style:''} · ${i.kind||'icon'}`;$('#detailName').textContent=i.label||i.name;$('#detailCode').textContent=i.raster?'Raster favicon / image asset':(i.code?`Unicode U+${String(i.code).toUpperCase()}`:(i.svg?'Editable SVG vector':'Font glyph'));$('#idValue').textContent=key(i);$('#glyphValue').textContent=i.char||'Not available';$('#htmlValue').textContent=i.html||'Not available';$('#cssValue').textContent=i.css||'Not available';$('#svgCopyButton').disabled=!i.svg;$('#glyphCopyButton').disabled=!i.char;$('#assetCopyButton').disabled=!i.raster;$('#assetValue').textContent=i.raster||'Not a raster asset';const f=$('#favoriteButton'),on=favorites.has(key(i));f.textContent=on?'★ Remove from favorites':'☆ Add to favorites';f.classList.toggle('on',on);details.showModal()}
$('#closeDialog').onclick=()=>details.close();document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>current&&copy(val(current,b.dataset.copy),`Copied ${b.dataset.copy}`));$('#favoriteButton').onclick=()=>{if(!current)return;favorites.has(key(current))?favorites.delete(key(current)):favorites.add(key(current));localStorage.setItem('omniIconFavorites',JSON.stringify([...favorites]));counts();open(current);render()};
function counts(){const kinds={ui:0,brand:0,developer:0,favicon:0};ICONS.forEach(i=>kinds[i.kind]=(kinds[i.kind]||0)+1);$('#count-all').textContent=ICONS.length.toLocaleString();$('#count-ui').textContent=(kinds.ui||0).toLocaleString();$('#count-brand').textContent=((kinds.brand||0)+(kinds.favicon||0)).toLocaleString();$('#count-developer').textContent=(kinds.developer||0).toLocaleString();$('#count-favorites').textContent=favorites.size.toLocaleString()}
document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==search){e.preventDefault();search.focus()}if(e.key==='Escape'&&details.open)details.close()});buildPacks();counts();render();
})();
